// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9JhhRNNC7UEHFm2NKNI5cF_AexyBfZkg',
    appId: '1:831697630789:web:3d521fa237e8ef0c77952c',
    messagingSenderId: '831697630789',
    projectId: 'svrkxmdvm',
    authDomain: 'svrkxmdvm.firebaseapp.com',
    storageBucket: 'svrkxmdvm.appspot.com',
    measurementId: 'G-T6QYT50H36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsM4udXa5LO57-BHrHqt1bqLXH3Y7mdcg',
    appId: '1:831697630789:android:22bbe50fb338479377952c',
    messagingSenderId: '831697630789',
    projectId: 'svrkxmdvm',
    storageBucket: 'svrkxmdvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBknfxQfSnFnOXHylT3ZGe7q2UYhx8O5o4',
    appId: '1:831697630789:ios:2389d940f60ecf6677952c',
    messagingSenderId: '831697630789',
    projectId: 'svrkxmdvm',
    storageBucket: 'svrkxmdvm.appspot.com',
    iosBundleId: 'svrkxmdvm.app.mvkun.svrkxmdvm',
  );
}
